# https://numtide.github.io/devshell
[[env]]
name = "KUBECONFIG"
eval = "$HOME/.kube/config"

[[commands]]
package = "pkgs.kubeconform"

[[commands]]
package = "pkgs.k9s"

[[commands]]
package = "pkgs.kubecm"

[[commands]]
package = "pkgs.just"

[[commands]]
package = "unstable.fluxcd"

[devshell]
packages = [
  "pkgs.kubernetes-helm-wrapped",
  "pkgs.helmfile-wrapped",
  "pkgs.treefmt",
  "pkgs.nixpkgs-fmt",
  "pkgs.taplo",
  "pkgs.yamlfmt",
  "pkgs.pre-commit",
  "pkgs.go-task",
]
